version: "3" ## especifica a versão do docker-compose file

services: ## Define um serviço
  db:
    container_name: 'db-api-freela'
    image: mysql:5.7
    restart: always
    environment:
      TZ: America/Sao_Paulo
      MYSQL_DATABASE: 'api-freela-typeorm'
      MYSQL_ROOT_PASSWORD: 'root'
    command: --default-authentication-plugin=mysql_native_password --sql_mode=NO_ENGINE_SUBSTITUTION,NO_AUTO_CREATE_USER --explicit_defaults_for_timestamp
    ports: 
      - '3309:3306'